version: "3.3"
services:
  hello-python:
    build: .
    container_name: tornado-app
    env_file: ${ENV}

    depends_on:
      - redis
    ports: 
      - "4222:8000"



  redis:
    image: redis
    container_name: redis-tornado
